import FWCore.ParameterSet.Config as cms
process = cms.Process("JetFlavourReader")
# process.MessageLogger.cerr.threshold = "INFO"
process.MessageLogger = cms.Service("MessageLogger",
    destinations = cms.untracked.vstring('cout', 'cerr'),  
    cout = cms.untracked.PSet(
        threshold = cms.untracked.string('INFO')  
    ),
    cerr = cms.untracked.PSet(
        threshold = cms.untracked.string('ERROR')  
    ),
)
process.load("FWCore.MessageService.MessageLogger_cfi")
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(1000000) )
process.source = cms.Source("PoolSource",
# replace 'myfile.root' with the source file you want to use
   fileNames = cms.untracked.vstring(
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_1.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_2.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_3.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_4.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_5.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_6.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_7.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_8.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_9.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_10.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_11.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_12.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_13.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_14.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_15.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_16.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_17.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_18.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_19.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_20.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_21.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_22.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_23.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_24.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_25.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_26.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_27.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_28.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_29.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_30.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_31.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_32.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_33.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_34.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_35.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_36.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_37.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_38.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_39.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_40.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_41.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_42.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_43.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_44.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_45.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_46.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_47.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_48.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_49.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_50.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_51.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_52.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_53.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_54.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_55.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_56.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_57.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_58.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_59.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_60.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_61.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_62.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_63.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_64.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_65.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_66.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_67.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_68.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_69.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_70.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_71.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_72.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_73.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_74.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_75.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_76.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_77.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_78.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_79.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_80.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_81.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_82.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_83.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_84.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_85.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_86.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_87.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_88.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_89.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_90.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_91.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_92.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_93.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_94.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_95.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_96.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_97.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_98.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_99.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_100.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_101.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_102.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_103.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_104.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_105.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_106.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_107.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_108.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_109.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_110.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_111.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_112.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_113.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_114.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_115.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_116.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_117.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_118.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_119.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_120.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_121.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_122.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_123.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_124.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_125.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_126.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_127.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_128.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_129.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_130.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_131.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_132.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_133.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_134.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_135.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_136.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_137.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_138.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_139.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_140.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_141.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_142.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_143.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_144.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_145.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_146.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_147.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_148.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_149.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_150.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_151.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_152.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_153.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_154.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_155.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_156.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_157.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_158.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_159.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_160.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_161.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_162.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_163.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_164.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_165.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_166.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_167.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_168.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_169.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_170.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_171.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_172.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_173.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_174.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_175.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_176.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_177.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_178.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_179.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_180.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part1/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_181.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_1.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_2.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_3.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_4.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_5.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_6.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_7.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_8.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_9.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_10.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_11.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_12.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_13.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_14.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_15.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_16.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_17.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_18.root",
        "file:/home/tiyang/public/TTHH_sample/mc/Run3Summer23MINIMAOD/TTHH_DL_BBVV_3_part2/step4_TTHH_DL_LO_incluTau_2B2V_dipole_recoil_19.root"
   )
)

# for fileoutput
process.JetFlavourReader = cms.EDAnalyzer('JetFlavourReader')
process.JetFlavourReader.outFileName = cms.untracked.string('/home/tiyang/public/rDataFrameLight_git/DNN_input/bjetDNN/bjet_assignment_DNN_info_TTHHDL_2023.csv')
process.JetFlavourReader.slimmedJets = cms.InputTag("slimmedJets")
process.JetFlavourReader.slimmedGenJets = cms.InputTag("slimmedGenJets")
process.JetFlavourReader.slimmedGenJetsFlavourInfos = cms.InputTag("slimmedGenJetsFlavourInfos")
process.JetFlavourReader.slimmedMuons = cms.InputTag("slimmedMuons")
process.JetFlavourReader.offlineSlimmedPrimaryVertices = cms.InputTag("offlineSlimmedPrimaryVertices")
process.p = cms.Path(process.JetFlavourReader)